apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: apps.platform.upbound.io
spec:
  group: platform.upbound.io
  scope: Namespaced
  names:
    categories:
    - crossplane
    kind: App
    plural: apps
  versions:
  - name: v1
    referenceable: true
    schema:
      openAPIV3Schema:
        description: App is the Schema for the App API.
        properties:
          spec:
            description: AppSpec defines the desired state of App.
            properties:
              parameters:
                properties:
                  deployment:
                    properties:
                      replicaCount:
                        type: number
                      image:
                        properties:
                          repository:
                            type: string
                          pullPolicy:
                            type: string
                          tag:
                            type: string
                        type: object
                      podAnnotations:
                        additionalProperties:
                          type: string
                        type: object
                      podLabels:
                        additionalProperties:
                          type: string
                        type: object
                      podSecurityContext:
                        properties:
                          fsGroup:
                            type: integer
                        type: object
                      securityContext:
                        properties:
                          capabilities:
                            properties:
                              drop:
                                items:
                                  type: string
                                type: array
                            type: object
                          readOnlyRootFilesystem:
                            type: boolean
                          runAsNonRoot:
                            type: boolean
                          runAsUser:
                            type: integer
                        type: object
                      resources:
                        properties:
                          limits:
                            additionalProperties:
                              type: string
                            type: object
                          requests:
                            additionalProperties:
                              type: string
                            type: object
                        type: object
                      livenessProbe:
                        properties:
                          httpGet:
                            properties:
                              path:
                                type: string
                              port:
                                type: string
                            type: object
                          initialDelaySeconds:
                            type: integer
                          periodSeconds:
                            type: integer
                        type: object
                      readinessProbe:
                        properties:
                          httpGet:
                            properties:
                              path:
                                type: string
                              port:
                                type: string
                            type: object
                          initialDelaySeconds:
                            type: integer
                          periodSeconds:
                            type: integer
                        type: object
                      volumes:
                        items:
                          properties:
                            name:
                              type: string
                            configMap:
                              properties:
                                name:
                                  type: string
                              type: object
                            secret:
                              properties:
                                secretName:
                                  type: string
                                optional:
                                  type: boolean
                              type: object
                          type: object
                        type: array
                      volumeMounts:
                        items:
                          properties:
                            name:
                              type: string
                            mountPath:
                              type: string
                            readOnly:
                              type: boolean
                          type: object
                        type: array
                      nodeSelector:
                        additionalProperties:
                          type: string
                        type: object
                      tolerations:
                        items:
                          properties:
                            key:
                              type: string
                            operator:
                              type: string
                            value:
                              type: string
                            effect:
                              type: string
                          type: object
                        type: array
                      affinity:
                        properties:
                          nodeAffinity:
                            properties:
                              requiredDuringSchedulingIgnoredDuringExecution:
                                properties:
                                  nodeSelectorTerms:
                                    items:
                                      properties:
                                        matchExpressions:
                                          items:
                                            properties:
                                              key:
                                                type: string
                                              operator:
                                                type: string
                                              values:
                                                items:
                                                  type: string
                                                type: array
                                            type: object
                                          type: array
                                      type: object
                                    type: array
                                type: object
                            type: object
                        type: object
                      autoscaling:
                        properties:
                          enabled:
                            type: boolean
                          minReplicas:
                            type: number
                          maxReplicas:
                            type: number
                          targetCPUUtilizationPercentage:
                            type: number
                        type: object
                    type: object
                  imagePullSecrets:
                    items:
                      type: object
                    type: array
                  nameOverride:
                    type: string
                  fullnameOverride:
                    type: string
                  serviceAccount:
                    properties:
                      create:
                        type: boolean
                      automount:
                        type: boolean
                      annotations:
                        additionalProperties:
                          type: string
                        type: object
                      name:
                        type: string
                    type: object
                  service:
                    properties:
                      type:
                        type: string
                      port:
                        type: number
                    type: object
                  ingress:
                    properties:
                      className:
                        type: string
                      annotations:
                        additionalProperties:
                          type: string
                        type: object
                      hosts:
                        items:
                          properties:
                            host:
                              type: string
                            paths:
                              items:
                                properties:
                                  path:
                                    type: string
                                  pathType:
                                    type: string
                                type: object
                              type: array
                          type: object
                        type: array
                      tls:
                        items:
                          properties:
                            secretName:
                              type: string
                            hosts:
                              items:
                                type: string
                              type: array
                          type: object
                        type: array
                    type: object
                type: object
            type: object
          status:
            description: AppStatus defines the observed state of App.
            type: object
        required:
        - spec
        type: object
    served: true
