---
apiVersion: meta.pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-template-typescript-function
  annotations:
    meta.crossplane.io/maintainer: Crossplane Maintainers <info@crossplane.io>
    meta.crossplane.io/source: https://github.com/crossplane/function-template-typescript
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This function is an example Crossplane function written in Typescript.
    meta.crossplane.io/readme: |
      See https://github.com/crossplane/function-template-typescript/blob/main/README.md for
      customizing this function.
spec:
  capabilities:
    - composition